services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: ""
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings

  - type: worker
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8155139765:AAHUTF9FcQ7SYqpDRMFR1VaCtcxyhl3F2Vg