# Generated by Django 5.2.1 on 2025-05-11 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBalance',
        ),
    ]
