# Generated by Django 5.2.1 on 2025-05-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_claimed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=12),
        ),
    ]
