# Generated by Django 5.2.1 on 2025-05-26 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customuser_last_claimed_alter_customuser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_claimed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
