# Generated by Django 5.2.1 on 2025-06-03 17:30

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_customuser_last_claimed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_claimed',
            field=models.DateTimeField(default=myapp.models.default_last_claimed),
        ),
    ]
