# Generated by Django 5.2.1 on 2025-07-10 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_business_dailyrevenue_userbusiness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
