# Generated by Django 5.2.1 on 2025-06-05 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='purchased_products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_bought',
        ),
        migrations.AddField(
            model_name='product',
            name='supply',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
