# Generated by Django 5.2.1 on 2025-06-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_productlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
